### ISSUE TITLE
Backslash + Special Char = Shifted Highlight

### ISSUE THREAD

**Issue by dejanzelic** [davidlday/vscode-languagetool-linter#132]
**Describe the bug**
When, for example, a "\\_" is added in a document, the remaining text is shifted by amount of "\\_". This isn't only on "\\_" but any combination of backslash + some special chars. For example: "\\;" or "\\-" 

**To Reproduce**
1. Write a document with some level of spelling/grammar errors
2. Before the errors, write "\\_"
3. Observe errors after "\\_" are not highlighted as expected. 

**Expected behavior**
The Highlights should stay consistent regardless of the text that is used. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5379480/80996149-33464000-8df4-11ea-9ae3-d30043d75b94.png)

**Environment & Configuration (please complete the following information):**
 - OS + Version: Mac 10.15.4
 - VS Code Version: 1.44.2
 - LanguageTool Linter Version: 0.12.0
 - LanguageTool Version: 4.9.1 (https://github.com/silvio/docker-languagetool)
 - Service Configuration: external

**Comment by davidlday** [comment]
Thanks for the bug report! Bumping this to the top of my list and tagging as possible cause of #120

**Comment by davidlday** [comment]
LanguageTool server accepts JSON in a form data field (application/x-www-form-urlencoded). This URL encoding sees slashes as escaping the next character if it's one of the special characters. I may need to open an issue on LanguageTool. I think if they're going to accept JSON, but need to explore more.

**Comment by davidlday** [comment]
Seems to be related to https://github.com/remarkjs/remark/issues/306 from 2017. Will continue to see if there's a workaround I can implement.

**Comment by davidlday** [comment]
After thinking this through and testing out a few approaches, I've decided to address in the `annotatedtext-remark` library directly. The problem stems from the parser used there, and trying to fix it here corrupts the code.

Ref: https://github.com/prosegrinder/annotatedtext-remark/issues/26

**Comment by dejanzelic** [comment]
Thanks for the update!!
