### ISSUE TITLE
Publish extension to Open VSX Registry

### ISSUE THREAD

**Issue by ebramirez** [davidlday/vscode-languagetool-linter#182]
**Is your feature request related to a problem? Please describe.**
Other IDEs based on Eclipse Theia (The engine behind VS Code) like VSCodium, Eclipse Che, GitPod, etc, use [Open VSX Registry](https://open-vsx.org) instead of the proprietary VS Code Marketplace, so this plugin is not available for those using them.

**Describe the solution you'd like**
I would like that the plugin is deployed to the Open VSX Registry upon release, like it is currently done for the VS Code Marketplace.

The procedure is documented [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by davidlday** [comment]
@bramirez - latest version is published. I've added automation to publish to both Marketplace and Open VSX as well. Leaving this open until I've had a chance to test the automation.

**Comment by ebramirez** [comment]
Thanks!

**Comment by davidlday** [comment]
Publish automation successful for v0.16.0.
