### ISSUE TITLE
Wrong port in docker command line

### ISSUE THREAD

**Issue by damienleroux** [davidlday/vscode-languagetool-linter#205]
**Describe the bug**
The Readme.md port for the docker local service is 8001 but should be 8081 on line https://github.com/davidlday/vscode-languagetool-linter/blame/master/README.md#L47

**To Reproduce**
Run the docker instance with the provided command line. The linter won't work with the default parameters.

**Expected behavior**
Run the docker on the default port 8081 instead of 8001:

```console
docker run --rm  -p 8081:8010 silviof/docker-languagetool
```

**Comment by davidlday** [comment]
Fixed in 0.17.0.
