### ISSUE TITLE
Multiple rules are not getting ignored

### ISSUE THREAD

**Issue by anishmittal2020** [davidlday/vscode-languagetool-linter#217]
**Describe the bug**
Multiple rules are not getting ignored when set up in the vscode settings, see screenshots

**To Reproduce**
See the screenshots

**Expected behavior**
Multiple rules to be ignored

**Screenshots**
With `EN_QUOTES, DASH_RULE`, the  `DASH_RULE` is not ignored as follows:

![image](https://user-images.githubusercontent.com/42092626/102833090-75a6a680-43f0-11eb-9991-443468de0b62.png)

With `DASH_RULE, EN_QUOTES`, the ` EN_QUOTES` is not ignored:

![image](https://user-images.githubusercontent.com/42092626/102833176-a1299100-43f0-11eb-88e6-54bee4c22e86.png)

**Environment & Configuration (please complete the following information):**
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:23:33.049Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-58-generic
 - LanguageTool Linter Version: 0.16.0
 - Service Configuration: [e.g. external, public, managed]: public

**Comment by davidlday** [comment]
@anishmittal2020 Thanks for submitting this!

I have an enhancement on my list (#67) that would change how ignored rules are managed so they're managed similar to how ignored words are managed. I expect to have this completed by end of January. Since you're the first one to point out this is broken (and apparently has been the whole time), I feel like focusing on the enhancement, which would fix this bug, is a higher priority. What do you think?

**Comment by davidlday** [comment]
@anishmittal2020 - Sorry, had a question, too. Do you have "Disabled Rules" set at both the User and Workspace levels?

**Comment by anishmittal2020** [comment]
@davidlday Only in User level, I have set disabled rules.

Ok, if you think the enhancement is a priority, then we don't need to duplicate the efforts in correcting the error.

**Comment by davidlday** [comment]
I have looked into this more, and I think it needs to be fixed. The enhancement I mentioned above shouldn't be used to replace disabling rules on the server side. This fix is at the top of my list now.

**Comment by davidlday** [comment]
@anishmittal2020  - It seems the LanguageTool server doesn't like having spaces after the commas. So `DASH_RULE,PROFANITY` works, but `DASH_RULE, PROFANITY` does not. Can you let me know if you see this behavior too, pls?

**Comment by davidlday** [comment]
Changed to enhancement. Not much I can do other than test the values and show a warning if there are spaces. LanguageTool expects comma separated IDs with no spaces.

**Comment by anishmittal2020** [comment]
> @anishmittal2020 - It seems the LanguageTool server doesn't like having spaces after the commas. So `DASH_RULE,PROFANITY` works, but `DASH_RULE, PROFANITY` does not. Can you let me know if you see this behavior too, pls?

Yes you are right.
