### ISSUE TITLE
Specify Language IDs to Consider "Plain Text"

### ISSUE THREAD

**Issue by davidlday** [davidlday/vscode-languagetool-linter#22]
Consider adding settings to enable/disable for specific document types of markdown, HTML, and plain text.

**Comment by davidlday** [comment]
Updated Approach: Add a setting for 'languageIds', similar to the [write-good](https://github.com/TravisTheTechie/vscode-write-good/) extension to give full control over which languageIds are linted to the end user. This seems like the most versatile approach, and will let users lint documents not explicitly supported as plain text documents.

**Comment by NeoScaler** [comment]
This would also fix #95, as you could simply activate AsciiDoc language support.

**Comment by davidlday** [comment]
User should be able to enable / disable linting "Plain Text" documents, meaning the whole document is sent to LanguageTool as-is. User should be able to provide a custom list of Language IDs that should be considered "Plain Text", with a default of `plaintext`.
