### ISSUE TITLE
Ltex does not check the whole document

### ISSUE THREAD

**Issue by rhadamants** [davidlday/vscode-languagetool-linter#341]
Using Ltex or local languagetool server, the extension does not check the whole document. It checks 10900 characters in the server log and stops.

How can I set it to check the whole document or in parts like the extension for GoogleDocs does by checking every page?
[djyt0000.txt](https://github.com/davidlday/vscode-languagetool-linter/files/7109892/djyt0000.txt)

**Comment by davidlday** [comment]
Are you referring to the [LTeX](https://github.com/valentjn/vscode-ltex) extension? If so, you'll need to ask over on their repository.

The character limit is set on the service itself, and not through this extension:

```bash
$ languagetool-server --help
Usage: HTTPServer [--config propertyFile] [--port|-p port] [--public]
  --config FILE  a Java property file (one key=value entry per line) with values for:
                 'maxTextLength' - maximum text length, longer texts will cause an error (optional)
                 'maxTextHardLength' - maximum text length, applies even to users with a special secret 'token' parameter (optional)
...
```

**Comment by rhadamants** [comment]
The same goes for its extension.
The file is checked, but the blue underline effect of its extension does not appear throughout the text.
The same happens with the LteX extension.

With the blue underline effect I can click and look at the LanguageTool suggestions.
As text doesn't get this effect I can only check the first 2600 characters and only guess at the rest. Why is it that where there are errors if I click on it, the suggestions appear even if it is not underlined with the effect.

My LanguageTool server is not character limited.
It is only the blue effect where there are errors that does not appear in the full text.

**Comment by davidlday** [comment]
Can you add a screenshot of your "Output" window in VS Code? I see a message at the bottom saying "Not showing 802 further errors and warnings." Are you seeing the same?

This is a limitation of VS Code: https://github.com/Microsoft/vscode/issues/48082

**Comment by rhadamants** [comment]
![Captura de tela 2021-09-06 152516](https://user-images.githubusercontent.com/9261306/132252373-9272811f-7cf9-442e-83b6-0dd62b99a7cd.png)

is it?

**Comment by rhadamants** [comment]
[https://i.imgur.com/603fYx4.png](url)

The text below the effect appears only this balloon on line 102 where the word "est" has a spelling error.

**Comment by davidlday** [comment]
On the bottom, change to "Problemas" tab, then scroll to the bottom of the list of problems. Here's a screenshot of what I see. 

<img width="1791" alt="Screen Shot 2021-09-06 at 2 32 52 PM" src="https://user-images.githubusercontent.com/1132144/132252973-eb4a94d5-539e-4cf0-a974-b0f4e1f0764d.png">

**Comment by rhadamants** [comment]
These are the spelling problems to correct.
Most of them are from having English words together with words in en-BR.

Should this limit the use of the extension?

**Comment by davidlday** [comment]
And yes, it is a limitation of VS Code. This is stated explicitly here: https://github.com/microsoft/vscode/issues/48082#issuecomment-382636401

Consider disabling the "DOUBLE_PUNCTUATION" rule to prevent the overload from happening.

**Comment by rhadamants** [comment]
That's it.
After I disabled the rule it worked.
Thanks for your help.

Is it possible to configure the extension to work with English and pt-BR?

**Comment by davidlday** [comment]
Glad to help, and to hear it's working now.

As far as I know, no, LanguageTool cannot check multiple languages at the same time. You might ask over at the LanguageTool forum: https://forum.languagetool.org/
