### ISSUE TITLE
No correction

### ISSUE THREAD

**Issue by noraj** [davidlday/vscode-languagetool-linter#633]
**Describe the bug**

That's as hard to describe as "LT linter is no longer working". I have a LT Server running on default http://localhost:8081. The server is running (I can see with systemctl, contacting the URL, etc.) and working with Firefox extension for example. However it's not working with the VScode extension while it's correctly configured (external, right URL). I open markdown or text files, write literally some garbage and on save there are no issues.

I don't see any extension error in VScode, the only thing I see are on the LT server logs with journalctl:

```
sept. 17 14:13:20 archpowa languagetool[584]: WARN  o.l.l.i.DefaultLanguageIdentifier Cannot consider noopLanguages because not in fastText mode: [en, fr]
```

**To Reproduce**

Hard to tell.

**Expected behavior**

Working as it was before.

**Environment & Configuration**

- OS + Version: ArchLinux (linux 6.5.3)
- VS Code Version: 1.82.1
- LanguageTool Linter Version: 0.20.0
- LanguageTool Version: 6.2
- Service Configuration: external

```
Version: 1.82.1
Commit: 6509174151d557a81c9d0b5f8a5a1e9274db5585
Date: 2023-09-16T10:07:32.958Z
Electron: 25.6.0
ElectronBuildId: undefined
Chromium: 114.0.5735.134
Node.js: 18.15.0
V8: 11.4.183.23-electron.0
OS: Linux x64 6.5.3-arch1-1
```

**Comment by noraj** [comment]
PS: I had LT linter working on another computer and updating ArchLinux (`pacman -Syu`) and restarting LT linter no longer works but I don't see from which package upgrade it would come.

**Comment by X52p** [comment]
@noraj does "Force Check as Plain Text Document" work for you? If yes, do the quick fix suggestions work?
(I seem to have a similar problem and try to find out if it is the same problem)

My Environment & Configuration:
- OS + Version: Windows 10
- VS Code Version: 1.84.2
- LanguageTool Linter Version: 0.20.0
- LanguageTool Version: 6.3 (and also tested with 6.2)
- Service Configuration: managed

**Comment by noraj** [comment]
This suddenly works again.

Also, I'm not sure which option you are talking about, this one is enabled by default.

![image](https://github.com/davidlday/vscode-languagetool-linter/assets/16578570/b4e12564-3a8c-4eb0-8038-c5b857015b35)

**Comment by noraj** [comment]
I'll close this issue at it is no longer happening, is not reproducible and the root cause was not identified.

**Comment by noraj** [comment]
Also I saw this today.

![image](https://github.com/davidlday/vscode-languagetool-linter/assets/16578570/5871be13-05a1-4c6c-905a-edd3b3be144d)
