### ISSUE TITLE
files get linted upon opening despite `"languageToolLinter.enabled": false`

### ISSUE THREAD

**Issue by j-lakeman** [davidlday/vscode-languagetool-linter#699]
**To Reproduce**
1. `"languageToolLinter.enabled": false`
2. `"languageToolLinter.lintOnOpen": true`
3. files get linted upon opening

**Expected behavior**
 `"languageToolLinter.enabled": false` should take precedence over `"languageToolLinter.lintOnOpen": true`

**Comment by davidlday** [comment]
Thanks for reporting this issue!

This looks like I left a legacy setting in there. VS Code provides the ability to enable/disable extensions in a workspace directly. If you go to Extensions and the Languagetool Linter, you should be able to right click and see "Disable (Workspace)" on the context menu that shows up. Before I remove the config item from the extension itself, can you verify that using the built-in feature works and addresses your problem, please?

![image](https://github.com/user-attachments/assets/82cab21c-47f8-410c-a3ac-0bffafa7c038)

If this addresses the issue, I'll remove the legacy config item as it'll continue to cause confusion.

**Comment by j-lakeman** [comment]
Confirming _Disable (Workspace)_ working as expected.

**Comment by davidlday** [comment]
Excellent. I'm leaving this open until I get that old config item out.
