### ISSUE TITLE
Toggle to enable/disable the linter temporarily

### ISSUE THREAD

**Issue by Prodeguerriero** [davidlday/vscode-languagetool-linter#750]
**Is your feature request related to a problem? Please describe.**
I mainly use this linter when editing Markdown files, which are also being linted for Markdown-related rules. Sometimes it would be handy to not have both linting happening at the same time.
Or in general, there will be situation where I will want to ignore some rules in a file, without adding the exceptions in the file.

**Describe the solution you'd like**
A toggle that allows me to disable LanguageTool linting on the fly. Like this one for the [Markdown linter](https://github.com/DavidAnson/vscode-markdownlint?tab=readme-ov-file#disable).

**Describe alternatives you've considered**
I have looked at this repo and the extension settings, to figure out if I am doing something wrong, and there's already a solution to my issue. Something like adding an “ignore” file to the workspace, for example. But I have come up empty-handed.
For now, I am stuck with disabling the extension for the entire workspace.

**Additional context**
N/A

**Comment by davidlday** [comment]
Thanks for the feature request!

I should be able to fit this in relatively soon. Sounds pretty simple.

**Comment by Prodeguerriero** [comment]
Great, let me know if I can assist in any way.
