### ISSUE TITLE
Report spell problems as info instead of warning

### ISSUE THREAD

**Issue by jseto** [davidlday/vscode-languagetool-linter#79]
When developing, _Errors_ and _Warnings_, are very useful but if _warnings_ start to be very populated with non programming related issues it becomes annoying and useless.  

**CSpell** is a nice tool to detect spelling issues in code. It reports problems as _info_ and does not distract in the programming process.

**Comment by davidlday** [comment]
I can add an option to let the user select the log level for errors. Would that work?

**Comment by jseto** [comment]
**Will be great!**

I feel sorry I cannot help you too much. Just give you my thoughts. I just moved to vsCode a week ago from Atom. No idea on how to develop extensions for vsCode. Should learn quickly. :)
