### ISSUE TITLE
Lint on file open as an option

### ISSUE THREAD

**Issue by jseto** [davidlday/vscode-languagetool-linter#80]
Many times, a file is opened only to be read or just to check something but not have the intention to work on it.

Opening many files, starts to populate the problems window and does not allow concentrating on the file you are working on.

If the linter works only _on save_ or _on user request_ this problem will disappear.

I think that it should be considered to set up an option to disable _lint on load_.

**Comment by davidlday** [comment]
I think I can add options flags to let the user select when linting occurs. Will look into it.
