### ISSUE TITLE
Allow to lint unsupported filetypes

### ISSUE THREAD

**Issue by pomdtr** [davidlday/vscode-languagetool-linter#96]
A quick pass of the linter on unsupported languages could be useful to quickly correct grammar mistakes, even with false positive (By using the command `Lint current document`).
Currently the workaround I found is to convert file to txt extension to be able to lint my files, but it is far from ideal.

**Comment by pomdtr** [comment]
Duplicate of #22, sry :-/

**Comment by davidlday** [comment]
No worries! I updated #22 to reflect this request as well. Great suggestion, BTW.
